### ISSUE TITLE
Declaration of Jenssegers\Mongodb\Relations\BelongsToMany::create should be compatible with...

### ISSUE THREAD

**Issue by TVolly** [jenssegers/laravel-mongodb#1259]
Uncaught Exception ErrorException: "Declaration of Jenssegers\Mongodb\Relations\BelongsToMany::create(array $attributes, array $joining = Array, $touch = true) should be compatible with Illuminate\Database\Eloquent\Relations\BelongsToMany::create(array $attributes = Array, array $joining = Array, $touch = true)"

https://github.com/jenssegers/laravel-mongodb/blob/v3.2.2/src/Jenssegers/Mongodb/Relations/BelongsToMany.php#L94
https://github.com/laravel/framework/blob/5.4/src/Illuminate/Database/Eloquent/Relations/BelongsToMany.php#L743

array $attributes   vs   array $attributes = []

added https://github.com/laravel/framework/commit/f59f6b29539fe149841c1f88bb5ad3d97e0403c0#diff-fac59ee2778e54567a539e9140a1a42cR743

**Comment by TVolly** [comment]
Fixed in v5.4.32 
https://github.com/laravel/framework/pull/20407/files

**Comment by appleinautumn** [comment]
It's not fixed on Lumen 5.5. On lumen 5.4, it's working fine.

**Comment by andrewjameshough** [comment]
This still hasn't been fixed in laravel 5.5.x either :/

**Comment by sagargulati** [comment]
Any update on the fix @jenssegers ?
