### ISSUE TITLE
ErrorException in DatabaseTokenRepository.php when using native laravel auth

### ISSUE THREAD

**Issue by mbordash** [jenssegers/laravel-mongodb#493]
Hi,

Native auth appears to work well until I load the password reminder link.   I get the exception:

ErrorException in DatabaseTokenRepository.php line 123:
strtotime() expects parameter 1 to be string, array given
in DatabaseTokenRepository.php line 123
at HandleExceptions->handleError('2', 'strtotime() expects parameter 1 to be string, array given', '/test/vendor/laravel/framework/src/Illuminate/Auth/Passwords/DatabaseTokenRepository.php', '123', array('token' => array('_id' => object(MongoId), 'email' => 'michael@email.com', 'token' => '<redacted>', 'created_at' => array('date' => '2015-05-14 15:42:46.000000', 'timezone_type' => '3', 'timezone' => 'UTC'))))

I've added "'Jenssegers\Mongodb\Auth\PasswordResetServiceProvider'," to my providers.  Hopefully I missed something simple.

Regards,

Michael

**Comment by jenssegers** [comment]
What Laravel version are you using?

**Comment by mbordash** [comment]
Laravel Framework version 5.0.30

**Comment by caseycs** [comment]
I think you forgot to add

```
'Jenssegers\Mongodb\Auth\PasswordResetServiceProvider',
```

In `app/config.php`, `providers` section.

**Comment by adzymaniac** [comment]
Hi
I'm using Laravel 5.1.4 and this thing not working.
```
ErrorException in DatabaseTokenRepository.php line 126: strtotime() expects parameter 1 to be string, array given
in DatabaseTokenRepository.php line 126
at HandleExceptions->handleError('2', 'strtotime() expects parameter 1 to be string, array given', '/App/vendor/laravel/framework/src/Illuminate/Auth/Passwords/DatabaseTokenRepository.php', '126', array('token' => array('_id' => object(MongoId), 'email' => 'hi@test.com', 'token' => '895e1c6f6f77a2540fb671865e3092e8cc1e0df3abba8b06a6c4865dcccb2504', 'created_at' => array('date' => '2015-07-03 07:38:59.000000', 'timezone_type' => '3', 'timezone' => 'UTC'))))
at strtotime(array('date' => '2015-07-03 07:38:59.000000', 'timezone_type' => '3', 'timezone' => 'UTC')) in DatabaseTokenRepository.php line 126
...
```

I've add the provider. Any suggestion?
```
Jenssegers\Mongodb\Auth\PasswordResetServiceProvider::class,
```

**Comment by lordcoste** [comment]
I've got the same error with lumen.

**Comment by lordcoste** [comment]
Has anyone found a workaround?

**Comment by dineshcooper** [comment]
Same error on Laravel 5.1.7, I do have the provider added.

**Comment by madmanlear** [comment]
Don't forget to create the password_resets collection and then test out the reset functionality from the beginning. This was the issue I can into, being a MongoDB rookie.

**Comment by artdarek** [comment]
I have same problem... i already have password_resets collection... any one knows how to fix that?

**Comment by wuori** [comment]
The timestamp being returned from Mongo is an array, which is passed directly into strtoTime(), which causes the error. Quick fix is to edit the line and reference the `date` index to read:

        $expirationTime = strtotime($token['created_at']['date']) + $this->expires;

Will see if I can find a better solution.

**Comment by wuori** [comment]
Upon further inspection, there were two mistake I saw:

1. I was putting my service providers at the top of the array instead of the bottom. Rookie mistake I hope.
2. My PHP wasn't recognizing the token as a MongoDate instance, causing it to bypass the mongodb provider override. 

In `vendor/jenssegers/mongodb/src/Jenssegers/Mongodb/Auth/DatabaseTokenRepository.php` I modified the tokenExpired function to look like this so that I could take my previous fix out of the default Laravel package:

    protected function tokenExpired($token)
    {
        // Convert MongoDate to a date string.
        if ($token['created_at'] instanceof MongoDate)
        {
            $date = new DateTime;

            $date->setTimestamp($token['created_at']->sec);

            $token['created_at'] = $date->format('Y-m-d H:i:s');

        }elseif(is_array($token['created_at']) && isset($token['created_at']['date'])){

           $token['created_at'] = $token['created_at']['date'];

        }

        return parent::tokenExpired($token);
    }

**Comment by wuori** [comment]
Fixed in PR #663

**Comment by zeroonnet** [comment]
I still have this issue.

I added the provider to the config.php but it still displays the same error "strtotime() expects parameter ....."

The code never gets inside the "DatabaseTokenRepository.php" that comes on this package, it's always including the "\Illuminate\Auth\Passwords\DatabaseTokenRepository" by default.
