### ISSUE TITLE
We need to do a better job of converting SQL LIKE expression into Regex

### ISSUE THREAD

**Issue by hackel** [jenssegers/laravel-mongodb#719]
In \Jenssegers\Mongodb\Query\Builder::compileWhereBasic, the conversion from an SQL LIKE expression to a MongoRegex is incomplete.  A quick search revealed a more complete implementation here: http://stackoverflow.com/a/11436643/4186945  Specifically, it should at least be calling preg_quote on the input parts that aren't operators (% and _).  You could leave quoting % and _ up to the developer, since that's what one would have to do with a SQL DB.

This bit me when trying to do a like query on an email address that contained a + character, that ends up going unescaped.  For now I'm just running preg_quote myself, but unfortunately that will break once this is fixed. :-/

**Comment by jenssegers** [comment]
Should be fixed in master :)

**Comment by hackel** [comment]
Brilliant, thanks.  This still doesn't cover % appearing mid-string, or _ at all, but I'm not using those personally.  Obviously people should be using a proper regex for that anyway.  This still allows me to use a library that runs a like query on my models.

**Comment by jenssegers** [comment]
It should. All `%`'s get replaced by `.*`

**Comment by hackel** [comment]
Bah, yes sorry, I was just testing and realised that.  Excellent!
