### ISSUE TITLE
whereHas with belongsToMany

### ISSUE THREAD

**Issue by Vagabondtq** [jenssegers/laravel-mongodb#803]
i used whereHas in Relationship belongsToMany, result is null.
it does not support?

**Comment by MRKiscaden** [comment]
I am running into the same problem where the whereHas with a subquery returns no results. See below:
$query->whereHas('tags', function ($q) use ($tagFilter) {
            $q->where('name', $tagFilter);
        });

I have a "tags" table which is a belongsToMany  relationship to another table called "Comments". When I try to get  all the "Comments" that have the tag with "name", I get no results. 

Is this feature broken?

**Comment by jffsn** [comment]
+1

**Comment by benargo** [comment]
Getting this aswell.

- Laravel Version: 5.3.30
- Laravel-MongoDB Version: 3.2.1
- PHP Version: 7.1.2

**Comment by vesper8** [comment]
can confirm this.. using whereHas on a mysql model with a hybrid relation to a mongo model causes the queries on the mongo model to be attempted on the mysql model which of course results in an error

any chance this can be fixed? it's also causing a problem, for the same reason as above, with one of my favourite eloquent libraries "tucker-eric/eloquentfilter"

**Comment by benargo** [comment]
Is this still causing issues? I believe I fixed this issue with #1158.

**Comment by alquesadilla** [comment]
Still an issue.
I am not using hybrid relations. 

https://stackoverflow.com/questions/46023352/laravel-mongo-many-to-many-relation-wherehas-not-working

**Comment by powerangelito** [comment]
Have you solved this ??

**Comment by sfaisal-modus** [comment]
Nope. Ended up using an additional query.
